language: python
python: "3.6"

install:
  - pip install -r requirements.txt

script:
  - set -e
  - make html
  - doctr deploy .

env:
  global:
    - secure: "BtzybJh3nr9Yl2FMHPL0h1j9L/xQBgZpWowBuh7BSBtQ+X0ud/0vqAyCI4ljivJtA6zyBAxitZsq0vc9F153L+ncYdcCLCJOxHJ12gtaz9WG+Qls5sVpLRZv33KwbMgsHoTRWWpV0VOimBBrjJmEFzcYizPRiu9aulmkZ1Y5M+A="
